"""enterprise baseline"""
from alembic import op
import sqlalchemy as sa
revision="20260812_0001";down_revision=None;branch_labels=None;depends_on=None
def upgrade():
 op.create_table("control_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("event_id",sa.String(100),nullable=False),sa.Column("event_type",sa.String(50),nullable=False),sa.Column("actor",sa.String(100),nullable=False),sa.Column("resource",sa.String(100),nullable=False),sa.Column("occurred_at",sa.String(40),nullable=False),sa.Column("payload_json",sa.Text(),nullable=False),sa.Column("evidence_hash",sa.String(64),nullable=False),sa.UniqueConstraint("tenant_id","event_id"));op.create_index("ix_control_events_tenant_id","control_events",["tenant_id"])
 op.create_table("control_policies",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("policy_code",sa.String(60),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("definition_json",sa.Text(),nullable=False),sa.Column("active",sa.Integer(),nullable=False),sa.UniqueConstraint("tenant_id","policy_code","version"));op.create_index("ix_control_policies_tenant_id","control_policies",["tenant_id"])
 op.create_table("audit_cases",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("event_id",sa.String(100),nullable=False),sa.Column("policy_code",sa.String(60),nullable=False),sa.Column("severity",sa.String(20),nullable=False),sa.Column("owner",sa.String(100)),sa.Column("status",sa.String(20),nullable=False),sa.Column("due_at",sa.String(40),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("evidence_hash",sa.String(64),nullable=False),sa.Column("version",sa.Integer(),nullable=False));op.create_index("ix_audit_cases_tenant_id","audit_cases",["tenant_id"])
 op.create_table("case_transitions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("case_id",sa.Integer(),nullable=False),sa.Column("from_status",sa.String(20),nullable=False),sa.Column("to_status",sa.String(20),nullable=False),sa.Column("actor",sa.String(100),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("occurred_at",sa.String(40),nullable=False));op.create_index("ix_case_transitions_tenant_id","case_transitions",["tenant_id"])
def downgrade():
 for table in ("case_transitions","audit_cases","control_policies","control_events"):op.drop_table(table)
